<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div>
        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Архитектура-режалаштириш топшириғи берилгани учун белгиланган</span></strong><br><strong><span style="font-family:'Times New Roman';">қўшимча йиғим тўловини амалга ошириш тўғрисидаги</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">АРТ-_________/24-сонли шартнома</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&nbsp;</span></p>
        <p style="margin-top:0pt; margin-bottom:6pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">Тошкент шаҳри</span><span style="width:9.37pt; font-family:'Times New Roman'; display:inline-block;">&nbsp;</span><span style="width:15.45pt; font-family:'Times New Roman'; display:inline-block;">&nbsp;</span><span style="width:35.4pt; font-family:'Times New Roman'; display:inline-block;">&nbsp;</span><span style="width:35.4pt; font-family:'Times New Roman'; display:inline-block;">&nbsp;</span><span style="width:35.4pt; font-family:'Times New Roman'; display:inline-block;">&nbsp;</span><span style="width:35.4pt; font-family:'Times New Roman'; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span><span style="width:29.4pt; font-family:'Times New Roman'; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">&nbsp;2024 йил________________________</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ldquo;Тошкент Инвест компанияси&rdquo; акциядорлик жамияти (кейинги ўринларда &mdash; Компания) номидан Устав асосида иш юритувчи Компания Бошқарув раиси в.б. Шакиров Бахром Аскаралиевич бир тарафдан, {{$client->company->company_name}} (кейинги ўринларда &mdash; Инвестор) номидан Устав асосида иш юритувчи {{$client->company->raxbar}} {{$client->last_name}} {{$client->first_name}} {{$client->father_name}} иккинчи тарафдан, биргаликда Тарафлар, алоҳида эса Тараф деб номланувчилар мазкур шартномани Ўзбекистон Республикаси Президентининг 2023 йил</span><br><span style="font-family:'Times New Roman';">26 июлдаги ПҚ-236-сон &ldquo;Тошкент шаҳрида давлат ва тадбиркорлик субъектлари ўртасида ўзаро манфаатли ҳамкорлик асосида инвестиция лойиҳаларини амалга ошириш ва шаҳар инфратузилмасини яхшилаш бўйича ҳуқуқий экспериментни ўтказиш чора-тадбирлари тўғрисида&rdquo;ги қарори, Вазирлар Махкамасининг 2024 йил 25 мартдаги 149-сон қарори билан тасдиқланган &ldquo;Тошкент шаҳрида муҳандислик-коммуникация тармоқлари ва транспорт инфратузилмасини яратиш харажатларининг бир қисмини шаҳарсозлик фаолияти объектини қуриш ёки реконструкция қилишни лойиҳалаштириш учун архитектура-режалаштириш топшириғини ишлаб чиқиш бўйича тўлов қийматига киритиш тартиби тўғрисида&rdquo;ги низом асосида қуйидагилар ҳақида имзоладилар:</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">I.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Шартнома предмети</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">1.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Компания Ўзбекистон Республикаси Президентининг 2023 йил 26 июлдаги &ldquo;Тошкент шаҳрини 2030 йилга қадар ижтимоий-иқтисодий ривожлантириш чора-тадбирлари тўғрисида&rdquo;ги ПФ-112-сон Фармонига мувофиқ Тошкент шаҳри ҳокимлиги ҳузуридаги Тошкент шаҳрини ривожлантириш жамғармаси (кейинги ўринларда &ndash; Жамғарма) маблағларини тасарруф этиш, ҳисоби ва ҳисоботини юритиш ваколати асосида мазкур шартномага мувофиқ, архитектура-режалаштириш топшириғи (кейинги ўринларда &ndash; АРТ) берилиши учун белгиланган қўшимча йиғим (кейинги ўринларда &ndash; Йиғим) тўлови Жамғарма томонидан мазкур шартнома асосида ўз вақтида қабул қилиб олинишини ташкил қилиш, Инвестор эса мазкур шартномада белгиланган Йиғим тўловини тегишли муддатларда ва ҳажмларда амалга ошириш мажбуриятини олади.</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">II.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Йиғим тўлови миқдори, тўлаш муддатлари ва шартлари</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">2.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Йиғим миқдори Ўзбекистон Республикаси Президентининг 2023 йил 26 июлдаги</span><br><span style="font-family:'Times New Roman';">ПҚ-236-сон &ldquo;Тошкент шаҳрида давлат ва тадбиркорлик субъектлари ўртасида ўзаро манфаатли ҳамкорлик асосида инвестиция лойиҳаларини амалга ошириш ва шаҳар инфратузилмасини яхшилаш бўйича ҳуқуқий экспериментни ўтказиш чора-тадбирлари тўғрисида&rdquo;ги қарори ҳамда Вазирлар Махкамасинининг 2024 йил 25 мартдаги 149-сон қарори билан тасдиқланган &ldquo;Тошкент шаҳрида муҳандислик-коммуникация тармоқлари</span><br><span style="font-family:'Times New Roman';">ва транспорт инфратузилмасини яратиш харажатларининг бир қисмини шаҳарсозлик фаолияти объектини қуриш ёки реконструкция қилишни лойиҳалаштириш учун АРТни ишлаб чиқиш бўйича тўлов қийматига киритиш тартиби тўғрисида&rdquo;ги низомга мувофиқ, жами қурилиш ҳажмининг ҳар бир куб метри учун базавий ҳисоблаш миқдорининг</span><br><span style="font-family:'Times New Roman';">1 баравари миқдорида, халқ депутатлари Тошкент шаҳар Кенгашининг</span><br><span style="font-family:'Times New Roman';">тегишли қарори ҳамда АРТ берилган лойиҳавий бино (иншоот) юзасидан ҳисоблаб чиқилган ва&nbsp;</span><a name="_Hlk166529944"><span style="font-family:'Times New Roman';">{{ number_format($branch->branch_kubmetr, 1) }} (__________________________) куб метр ҳажм учун&nbsp;</span></a><span style="font-family:'Times New Roman';">{{$branch->generate_price}}(______________________________) сўмни ташкил этади.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">2.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор йиғим миқдорини тўлиқ ҳажмда Жамғарма ҳисоб рақамига ўтказиш йўли билан мазкур шартнома имзоланган санадан бошлаб 3 (уч) иш кунидан кечиктирмаган ҳолда тўлашни амалга оширишни инобатга олган ҳолда мазкур шартномани имзолайди.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">2.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор йиғим миқдорини тўлиқ ҳажмда олдиндан тўлаш шарти билан Жамғарма ҳисоб рақамига ўтказиш йўли билан тўлайди.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">2.4.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартномада кўрсатилган ҳар қандай параметрлари ўзгарганда, улар ўзгарганлиги аниқланган (тасдиқланган) санадан бошлаб 5 (беш) иш куни мобайнида мазкур шартномага Йиғим миқдорини аниқлаштириш юзасидан тегишли ўзгартиришлар киритиш тўғрисидаги қўшимча келишув лойиҳасини илова қилган ҳолда Инвестор Компанияга ёзма равишда мурожаат қилади.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">Мазкур шартномада кўрсатилган ҳар қандай параметрлари қуйидаги асосларга кўра ўзгариши мумкин:</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ndash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">ундириладиган йиғим миқдорига нисбатан халқ депутатлари Тошкент шаҳар Кенгашининг қарори асосида камайтирувчи ёки оширувчи коэффициентлар қўлланилган тақдирда;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ndash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">мазкур шартномада кўрсатилган ҳар қандай параметрлари билан қонунчилик ҳужжатларига мувофиқ белгиланган тартибда олинган лойиҳа-смета ҳужжатлари экспертиза хулосаси натижасига мувофиқ параметрлари ўртасида фарқ юзага келган тақдирда;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ndash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">архитектура-қурилиш топшириғи берилган лойиҳавий бино (иншоот) юзасидан лойиҳа-смета ҳужжатлари экспертиза хулосасида кўрсатилган параметрлари билан қурилиши тугалланган бино (иншоот) фойдаланишга қабул қилинаётгандаги параметрлари ўртасида фарқ юзага келган тақдирда.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">Мурожаат натижасида Компания ва Инвестор мазкур шартноманинг</span><br><span style="font-family:'Times New Roman';">5.1&ndash;5.3-бандларида назарда тутилган ҳаракатларни амалга оширадилар.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">2.5.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор томонидан йиғим суммаси тўланганидан сўнг қуйидаги ҳолатларда Йиғим суммаси тўланган ҳажми қайтарилмайди:</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ndash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвесторга нисбатан амалдаги қонунчилик ҳужжатларида белгиланган тартибга мувофиқ банкротлик тартиботи жорий қилинганида;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ndash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор ўз ҳоҳишига ва (ёки) суд қарорига кўра тугатилган ҳамда фаолияти вақтинчалик тўхтатиб турилганда;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ndash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор ўз ҳоҳишига, суд қарори ёки ҳуқуқ-тартибот органларининг талабига кўра АРТ берилган лойиҳавий бинонинг (иншоотнинг) қурилишини тўхтатганда</span><br><span style="font-family:'Times New Roman';">ва (ёки) қурилишидан воз кечганда;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ndash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор ўз ҳоҳишига, суд қарори ёки ҳуқуқ-тартибот органларининг талабига кўра АРТ берилган лойиҳавий бинога (иншоотга) бўлган ҳуқуқларни ҳар қандай усул билан бошқа шахсларга ўтказганда, топширганда ёки бошқа шахсларнинг фойдасига воз кечганда;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ndash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Йиғим тўлаш мажбурияти бажарилиши билан боғлиқ бўлган ҳар қандай мажбуриятлари бажарилмаган бошқа ҳолларда.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">2.6.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Жамғарма банк реквизитлари: Ҳисобварақ: 22626000900101163001;</span><br><span style="font-family:'Times New Roman';">АҚШ долларида очилган ҳисобварақ: 22626840600101163001; EVROда очилган ҳисобварақ: 22626978100101163001; Россия RUBLида очилган ҳисобварақ: 22626643300101163001; Жамғарма СТИР: 201623064; Банк СТИР: 200547792; Банк коди: (МФО) 00433; Банк номи: &ldquo;Микрокредитбанк&rdquo; АТБ; Хизмат кўрсатувчи банк таркибий бўлинмаси: Тошкент шаҳар бошқармаси Тошкент шаҳар банк хизматлари офиси.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">2.7.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Лойиҳавий бино (иншоот) тури: {{$branch->branch_type}}.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">2.8.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Лойиҳавий бино (иншоот)нинг манзили:  {{$branch->branch_location}}.</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">III.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Тарафларнинг ҳуқуқлари ва мажбуриятлари&nbsp;</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартнома доирасида Компания қуйидагиларга мажбур:</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.1.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвесторнинг хўжалик фаолиятига аралашмаслик;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.1.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Йиғим тўлови амалга оширишда мустақил ва (ёки) Инвестор билан ҳамкорликда манфаатлар тўқнашуви ҳамда коррупция ҳолатларига йўл қўймаслик ва унинг олдини олишга қаратилган чоралар кўриш.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартнома доирасида Компания қуйидаги ҳуқуқларга эга:</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.2.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор томонидан мазкур шартнома шартлари бузилганлиги аниқланган тақдирда Инвестордан мазкур шартнома шартлари бузилишини бартараф этишни талаб қилиш;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.2.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор томонидан мазкур шартнома шартлари бузилган тақдирда мазкур шартномани белгиланган тартибда бир тарафлама бекор қилиш ва бу ҳақида Судга мурожаат қилиш;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.2.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Ўзбекистон Республикасининг амалдаги қонун ҳужжатларида белгиланган бошқа ҳуқуқларни амалга ошириш;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.2.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестордан лойиҳа ташкилоти томонидан архитектура-қурилиш топшириғи берилган лойиҳавий бино (иншоот) лойиҳа-смета ҳужжатларида ҳажм параметрлари батафсил кўрсатилишини талаб қилиш;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.2.4.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестордан мазкур шартномада кўрсатилган ҳар қандай параметрлари ўзгарганлигини (ўзгармаганлигини) тасдиқлаш билан боғлиқ бўлган ўрганиш (ўлчаш) ўтказилишини талаб қилиш.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартнома доирасида Инвестор қуйидагиларга мажбур:</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.3.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартномада белгиланган барча шартларга риоя қилган ҳолда Йиғим тўловини амалга ошириш;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.3.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Ўзбекистон Республикасининг амалдаги қонунчилик ҳужжатлари ва мазкур шартномада назарда бошқа мажбуриятларни бажариш;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.3.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Лойиҳа ташкилоти томонидан архитектура-қурилиш топшириғи берилган лойиҳавий бино (иншоот) лойиҳа-смета ҳужжатларида ҳажм параметрлари батафсил кўрсатилишини кафолатлаш;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.3.4.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартномада кўрсатилган ҳар қандай параметрлари ўзгарганлигини тасдиқлаш билан боғлиқ бўлган ҳар қандай асослантирилган сарф-харажатларни ўз ҳисобидан қоплашни кафолатлаш.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.4.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартнома доирасида Инвестор қуйидаги ҳуқуқларга эга:</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.4.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Компания томонидан Инвесторнинг мазкур шартнома шартларига риоя қилиниши юзасидан мониторинг ўтказилганида унда иштирок этиш ва мониторинг предметига оид масалалар бўйича тушунтиришлар бериш;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">3.4.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Ўзбекистон Республикасининг амалдаги қонунчилик ҳужжатларига мувофиқ Компаниядан олиниши мумкин бўлган маълумотларни сўраб олиш.</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><a name="_465177"></a><strong><span style="font-family:'Times New Roman';">IV.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Шартнома мажбуриятларини бажариш мониторинги</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">4.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор томонидан Йиғим тўланишини мониторинг қилиш Компания томонидан Жамғарма фаолиятига тегишли банк ва бухгалтерия ҳужжатлари асосида амалга оширилади.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">4.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Йиғим тўлашда камчиликлар аниқланган тақдирда Компания Инвесторга аниқланган камчиликларни ўз вақтида ва зудлик билан бартараф этиш юзасидан тегишли талабнома юборади ҳамда ушбу талабнома Инвестор томонидан 3 (уч) иш кунидан кечиктирмасдан қаноатлантирилиши лозим.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">4.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор томонидан Йиғим тўлаш муддати бузилганлиги Компания томонидан тузилган тегишли далолатнома билан тасдиқланади.</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">V.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Шартномани ўзгартириш ва муддатидан олдин бекор қилиш тартиби</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">5.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартнома Тарафлар келишувига кўра, шу жумладан лойиҳа-смета ҳужжатлари экспертиза хулосаси асосида тегишли ўзгартирилиши мумкин.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">5.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартномага ҳар қандай ўзгартиришлар ва қўшимчалар Тарафларнинг келишуви асосида Тарафларнинг ваколатли вакиллари имзолаган қўшимча келишувни имзолаш йўли билан киритилади.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">5.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Компания мазкур шартномани қуйидаги ҳолатлар юз берган тақдирда</span><br><span style="font-family:'Times New Roman';">ўз ташаббуси билан Йиғимнинг тўланган қисми юзасидан Инвесторга компенсация тўламасдан муддатидан олдин бир тарафлама бекор қилиш ҳуқуқига эга:</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">5.3.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">мазкур шартномага иловада келтирилган режа-график муддатлари</span><br><span style="font-family:'Times New Roman';">10 (ўн) иш кунидан ортиқ муддатга бузилганда;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">5.3.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">мазкур шартноманинг 8.1-бандида баён этилган ҳодисалар узлуксиз 6 (олти) ойдан ортиқ муддатга чўзилиб кетганда ва бу давом этганда;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">5.3.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор тугатилган ёки тўловга қобилиятсиз деб топилганда;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">5.3.4.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор томонидан ўз мажбуриятлари бажарилмаганида;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">5.3.5.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">мазкур шартномани имзолаш жараёнида ишончсиз ва/ёки ёлғон маълумотли ҳужжатларни Компанияга тақдим этган ҳолати аниқланганида.</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">VI.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Тарафларнинг жавобгарлиги</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:27pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">6.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор Компанияга қуйидаги ҳолатларда ва миқдорларда пеня тўлайди:</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:27pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ndash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Йиғим тўлови муддатларини бузганлик учун кечктирилган ҳар бир кун учун тўлови кечиктирилган Йиғим суммасининг 0,01</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">фоизи миқдорида, бироқ, тўлови кечиктирилган Йиғим суммасининг 15</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">%идан ортиқ бўлмаган миқдорда;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:27pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&ndash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартномада кўрсатилган ҳар қандай параметрлар ўзгарганда, улар ўзгарганлиги аниқланган (тасдиқланган) санадан бошлаб 5 (беш) иш куни мобайнида мазкур шартномага Йиғим миқдорини аниқлаштириш юзасидан тегишли ўзгартиришлар киритиш учун мазкур шартномага ўзгартиришлар киритиши тўғрисидаги қўшимча келишув лойиҳасини илова қилгани ҳолда Компанияга ёзма равишда мурожаат қилмаганда ҳар бир кечиккан кун учун Йиғим суммасининг 0,01 фоизи миқдорида, бироқ, тўлови кечиктирилган Йиғим суммасининг 15 фоизидан ортиқ бўлмаган миқдорда.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">6.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Жарима санкцияларининг қўлланилиши Инвесторни мазкур шартномада белгиланган мажбуриятларни бажаришдан озод қилмайди.&nbsp;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">6.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор қуйидаги ҳатти-ҳаракатларни содир этганида Компания мазкур шартномани бекор қилиш ҳақидаги талаб билан судга мурожаат қилади:</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&mdash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Йиғим тўлаш муддатларини белгиланган муддатдан уч ойдан ошиқ муддатга кечиктирганда;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&mdash;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор ўз ихтиёри билан тугатилганида ёки банкротликка учрганида,</span><br><span style="font-family:'Times New Roman';">шу жумладан, қасддан шундай ҳаракатлар амалга оширилиши туфайли Йиғим тўлашни дастлабки шартларда амалга ошириш имконияти мавжуд бўлмаслигига олиб келганида.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">6.4.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Инвестор томонидан мажбуриятлари бажарилмаслиги ёки у томонидан бошқа ҳаракатлар содир этилганлиги туфайли мазкур шартномани бекор қилиш пайтида Инвестор томонидан етказилган моддий зарар мустақил аудитор ва/ёки мустақил баҳоловчи томонидан тақдим этилган ҳисоб-китобларга асосан баҳоланади ва суд тартибида ундан ундирилади.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">6.5.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартноманинг амал қилиш муддати тугаши унинг бузилганлиги учун жавобгарликнинг тугатилишига олиб келмайди.</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">VII.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Манфаатлар тўқнашуви</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">7.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Компания ва Инвестор ходимлари ўз хизмат вазифаларини бажаришда манфаатлар тўқнашувига сабаб бўладиган шахсий манфаатдорлик ҳолатларига йўл қўймасликлари керак.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">7.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Манфаатлар тўқнашуви Компания ва Инвестор ходимларининг шахсий манфаатлари уларнинг ўз хизмат вазифаларини холисона ва беғараз бажаришига таъсир кўрсатадиган ёки таъсир кўрсатиши мумкин бўлган ҳолатларда пайдо бўлади.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">7.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Компания ва Инвестор ходимларининг шахсий манфаатдорлиги уларнинг шахсан ўзи ёки яқин қариндошлари, шунингдек улар яқин ёки ишбилармонлик муносабатларида бўладиган бошқа шахслар учун ҳар қандай наф кўриш ёки афзалликларга эга бўлишни</span><br><span style="font-family:'Times New Roman';">ўз ичига олади.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">7.4.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Манфаатлар тўқнашуви юзага келган тақдирда Компания ва Инвестор ходимлари ўз раҳбарини бу ҳақида дарҳол хабардор қилиши керак.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">7.5.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Манфаатлар тўқнашуви мавжудлиги тўғрисидаги маълумотни олган Тараф уни тартибга келтириш бўйича иккинчи Тараф билан ҳамкорликда ўз вақтида чоралар кўриши шарт.</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">VIII.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Форс-мажор</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">8.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Агар Тарафларнинг ўз мажбуриятларини бажармаслик ёки лозим даражада бажармаслик мазкур шартнома имзоланганидан сўнг Тарафлар олдиндан кўра билиши</span><br><span style="font-family:'Times New Roman';">ёки бартараф қилиши мумкин бўлмаган фавқулодда вазиятлар, шу жумладан, ҳарбий ҳаракатлар, эпидемиялар, блокадалар, эмбарголар, шунингдек, зилзила, сув тошқини, ёнғинлар ва бошқа табиий офатлар натижасида енгилмас куч таъсиридаги ҳолатлар билан боғлиқ бўлса, мазкур шартнома Тарафлари мазкур шартнома бўйича ўз мажбуриятларини бажармаганликлари ёки лозим даражада бажармаганликлари учун жавобгарликдан озод этиладилар.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">8.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Енгилмас куч таъсиридаги ҳолатлар юзага келган тақдирда Тараф ушбу ҳолатлар юзага келган пайтдан бошлаб 3 (уч) иш кунидан кечикмасдан бошқа Тарафни бу ҳақида хабардор қилишга мажбур. Бундай хабарда енгилмас куч таъсиридаги ҳолатлар характери ҳақидаги маълумотлар, шунингдек, уларнинг юзага келганини тасдиқловчи ҳужжатлар бўлиши лозим.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">8.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Тараф енгилмас куч таъсиридаги ҳолатлар юзага келгани ҳақидаги хабарни олган пайтдан бошлаб Тарафлар 30 (ўттиз) иш куни давомида енгилмас куч таъсиридаги ҳолатларнинг таъсирини камайтириш учун ўзаро ҳамкорликнинг энг самарали тартибини, шунингдек, мазкур шартнома шартларини ўзгартиришнинг энг мақбул усулларини белгилаб олишлари лозим.</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">IX.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Низоларни ҳал қилиш тартиби</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">9.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартномани бажариш давомида юзага келадиган ҳар қандай низолар</span><br><span style="font-family:'Times New Roman';">ва келишмовчиликлар Тарафлар ўртасида музокаралар йўли билан ҳал этилади.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">9.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Музокаралар орқали келишувга эришилмаган тақдирда манфаатдор Тараф иккинчи тарафга ёзма шаклда талабнома хат юборади.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">9.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Низолар Тарафлардан бирининг ёзма шаклдаги талабномаси юборилган санадан бошлаб 30 (ўттиз) иш куни давомида ҳал қилинмаган тақдирда ушбу низо Ўзбекистон Республикасининг амалдаги қонун ҳужжатларига мувофиқ суд тартибида ҳал этилади.</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">XI.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Алоҳида шартлар</span></strong></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">10.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Бир Тарафдан бошқа Тарафга берилган ахборотнинг махфийлик шартлари</span><br><span style="font-family:'Times New Roman';">ҳар қандай Тарафнинг ёзма талабига биноан белгиланиши мумкин. Махфий деб топилган</span><br><span style="font-family:'Times New Roman';">ҳар қандай ахборот ошкор қилинмаслиги лозим.</span></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">10.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Махфийлик шартлари қуйидаги ҳолатлар учун қўлланилмайди:</span></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">10.2.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">мазкур шартномани амалга ошириш мақсадида мазкур шартнома ва унинг шартлари тўғрисидаги ахборотни давлат органларига тақдим этишда;</span></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">10.2.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">бундай ахборот Ўзбекистон Республикасининг амалдаги қонун ҳужжатларига мувофиқ ёки Ўзбекистон Республикасининг давлат органлари ёки бошқа ваколатли органлари томонидан қонуний даъво тақдим этилганда фақат тушган сўров ҳажмида ошкор этилиши керак бўлганида.</span></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">10.3.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Почта реквизитлари ўзгарганда Тарафлар бир-бирларини дарҳол хабардор қилишлари керак. Эски манзиллар бўйича амалга оширилган ҳатти-ҳаракатлар, уларнинг ўзгариши ҳақида хабарнома олинмагунча қабул қилинган ҳисобланади.</span></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">10.4.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартнома шартлари ҳуқуқий оқибатларга олиб келиши ва ҳуқуқий ворислар, бенефициарлар ва Тарафлар томонидан тайинланган шахсларнинг келажакдаги барча кўринишлари ёки шакллари учун мажбурий бўлиши керак. Бундан ташқари, мазкур шартнома бўйича Тарафларнинг ҳуқуқ ва мажбуриятлари хўжалик жамиятларининг бошқа ташкилотлар билан бирлашуви, консолидация, қўшиб юбориш ёки Инвестор бошқарувида бошқача эгалик қилиш ёки ўзгартириш орқали бузилмаслиги керак.</span></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">10.5.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Тарафлар бошқа Тарафнинг ёзма розилигисиз бошқа шахсларга даъво қилиш</span><br><span style="font-family:'Times New Roman';">ёки ҳуқуқ ва мажбуриятларни бериш ҳуқуқини бера олмайди.</span></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">10.6.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартнома ва унга иловалар саҳифаларининг сони давлат тилида (ўзбек тилида) , икки асл нусхада тузилган, бир хил қонуний кучга эга бўлиб, асл нусхалардан бири Инвестор, иккинчиси эса Компания томонидан ўрнатилган тартибда сақланади.</span></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">10.7.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартномага иловалар мазкур шартноманинг ажралмас қисми ҳисобланади.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">10.8.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартномада назарда тутилмаган бошқа барча ҳолатлар Ўзбекистон Республикасининг амалдаги қонун ҳужжатлари асосида ҳал этилади.</span></p>
        <p style="margin-top:6pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">XI.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Шартноманинг кучга кириши ва амал қилиш муддати</span></strong></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:34.5pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">11.1.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартнома имзоланган санадан бошлаб кучга киради ва Тарафлар</span><br><span style="font-family:'Times New Roman';">ўз мажбуриятларини тўлиқ бажаргунларига қадар амал қилади.</span></p>
        <p style="margin-top:0.75pt; margin-bottom:0pt; text-indent:34.5pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Times New Roman';">11.2.</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Мазкур шартномадаги барча қоидалар Тарафлар учун имзоланган санадан бошлаб мажбурийдир.</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-indent:28.35pt; text-align:justify; line-height:normal; font-size:12pt;"><span style="font-family:'Times New Roman';">&nbsp;</span></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">XII.</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Тарафларнинг банк реквизитлари ва имзолари:</span></strong></p>
        <table cellspacing="0" cellpadding="0" style="width:496.15pt; border-collapse:collapse;">
            <tbody>
                <tr style="height:44.9pt;">
                    <td style="width:237.3pt; padding-right:5.4pt; padding-left:5.4pt; vertical-align:top;">
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">КОМПАНИЯ&nbsp;</span></strong></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">(Жамғарма банк реквизитлари)</span></strong></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Ҳисобварақ:</span></strong><span style="font-family:'Times New Roman';">&nbsp;(Сўмда) 22626000900101163001</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><span style="font-family:'Times New Roman';">АҚШ долларида: 22626840600101163001</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><span style="font-family:'Times New Roman';">EVROда: 22626978100101163001</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><span style="font-family:'Times New Roman';">Россия RUBLида: 22626643300101163001</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Жамғарма СТИР:</span></strong><span style="font-family:'Times New Roman';">&nbsp;201623064</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Банк СТИР:</span></strong><span style="font-family:'Times New Roman';">&nbsp;200547792</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Банк коди: (МФО)</span></strong><span style="font-family:'Times New Roman';">&nbsp;00433</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Банк номи:</span></strong><span style="font-family:'Times New Roman';">&nbsp;&ldquo;Микрокредитбанк&rdquo; АТБ</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Хизмат кўрсатувчи банк таркибий бўлинмаси:</span></strong><span style="font-family:'Times New Roman';">&nbsp;Тошкент шаҳар бошқармаси Тошкент шаҳар банк хизматлари офиси</span></p>
                        <div style="border-bottom-style:solid; border-bottom-width:1.5pt; clear:both;">
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><span style="font-family:'Times New Roman';">&nbsp;</span></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; padding-bottom:1pt; font-size:12pt;"><span style="font-family:'Times New Roman';">&nbsp;</span></p>
                        </div>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Шакиров Бахром Аскаралиевич</span></strong></p>
                    </td>
                    <td style="width:237.25pt; padding-right:5.4pt; padding-left:5.4pt; vertical-align:top;">
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">ИНВЕСТОР</span></strong></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Aдрес: {{$client->company->yuridik_address}}</span></strong></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Ҳисобварақ:</span></strong><span style="font-family:'Times New Roman';">&nbsp; {{$client->company->bank_account}}</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Банк коди:&nbsp;</span></strong><span style="font-family:'Times New Roman';">{{$client->company->bank_code}}</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Банк номи:&nbsp;</span></strong><span style="font-family:'Times New Roman';">{{$client->company->bank_service}}</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">СТИР:</span></strong><span style="font-family:'Times New Roman';">&nbsp;{{$client->company->stir}}</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">ОКЭД:</span></strong><span style="font-family:'Times New Roman';">&nbsp;{{$client->company->oked}}</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">Контакт:&nbsp;</span></strong><span style="font-family:'Times New Roman';">{{$client->contact}}</span></p>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><span style="font-family:'Times New Roman';">&nbsp;</span></p>
                        <div style="border-bottom-style:solid; border-bottom-width:1.5pt; clear:both;">
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                            <p style="margin-top:0pt; margin-bottom:0pt; padding-bottom:1pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                        </div>
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                    </td>
                </tr>
                <tr style="height:44.9pt;">
                    <td style="width:237.3pt; padding-right:5.4pt; padding-left:5.4pt; vertical-align:top;">
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                    </td>
                    <td style="width:237.25pt; padding-right:5.4pt; padding-left:5.4pt; vertical-align:top;">
                        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
                    </td>
                </tr>
            </tbody>
        </table>
        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
    </div>
    
</body>
</html>